services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - db_data:/var/lib/postgresql/data
  fetcher:
    build:
      context: .
      dockerfile: ./Fetcher/Dockerfile
    volumes: 
      - ../dataset:/dataset:ro # FIXME REMOVE THE COMMENT BEFORE UPLOAD TO MOODLE This is a bit hacky
    depends_on:
      - db
  rest_api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./REST_API/Dockerfile
    volumes: 
      - img:/img
    depends_on:
      - db
      - fetcher
  frontend:
    ports:
      - 5000:5000 # HOST:CONTAINER
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
      - rest_api

volumes:
  img:
  db_data: